
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Create Lists
        run: |
          make raws

      - name: Create SB3
        run: |
          make assemble
      
      - name: Upload Build
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Lists
          path: 'build/*'
